workspace: "exp/ecapa_tdnn_am"
trial_path: "data/vox1_clean.txt"
train_csv: "data/train.csv"
noise_csv: "data/noise.csv"
sample_rate: 16000
second: 2
batch_size: 200
num_workers: 40
save_top_k: 30
checkpoint_path: None
keep_loss_weight: True
spk_utt: 100
num_per_speaker: 1
trainer:
        max_epochs: 30
        gpus: 1
        accelerator: dp
        check_val_every_n_epoch: 1
feature: 
        name: "Mel_Spectrogram"
        coef: 0.97
        n_fft: 512
        win_length: 400
        hop: 160
        n_mels: 80
        requires_grad: False
backbone: 
        name: "ecapa_tdnn"
        embedding_dim: 192
        num_channels: 512
        n_mels: 80
loss:
        name: "aamsoftmax"
        embedding_dim: 192
        margin: 0.2
        scale: 30
optim:
        name: "Adam"
        lr: 0.001
        weight_decay: 0.00005
warmup_step: 500
schedule:
        name: "CyclicLR"
        base_lr: 0.00000001
        max_lr: 0.001
        step_size_up: 256
        step_size_down: 300
        cycle_momentum: False
