workspace: "exp"
trial_path: "data/trial.lst"
train_csv: "data/train.csv"
sample_rate: 16000
second: 1
batch_size: 300
num_workers: 16
save_top_k: 10
warmup_step: 500
keep_loss_weight: True
checkpoint_path: /home/zhangy20/torch_speaker/examples/voxceleb/exp/epoch=4_train_loss=0.87.ckpt
trainer:
        gpus: 0
        max_epochs: 15
        gpus: 1
feature: 
        name: "Mel_Spectrogram"
        coef: 0.97
        n_fft: 512
        win_length: 400
        hop: 200
        n_mels: 64
backbone: 
        name: "resnet34"
        embedding_dim: 256
        num_channels: [1, 32, 64, 128, 256]
        n_mels: 64
        pooling_type: "ASP"
#loss:
#        name: "softmax"
#        embedding_dim: 256
#        num_classes: 7205
loss:
        name: "amsoftmax"
        embedding_dim: 256
        num_classes: 7205
        margin: 0.2
        scale: 30
optim:
        name: "Adam"
        lr: 0.001
schedule:
        name: "MultiStepLR"
        milestones: [130,160,175,185]
        gamma: 0.1
